
version: '3'
services: 
    product-service:
        build: ./CodeKata/
        volumes:
            - ./CodeKata/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1